# --- Stage 1: Build & Dependency Installation
FROM python:3.14-alpine3.23 AS builder

# Install uv from the official image
COPY -from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Set working directory
WORKDIR /app

# Set env varialbes to prevent uv from creating virtual env
ENV PYTHONUSERBASE=/deps \
    UV_SYSTEM_PYTHON=1 \
    UV_COMPILE_BYTECODE=1
# PYTHONUSERBASE 
# What it is:a built-in Python environment variable. It lets you change the destination path for packages installed via the Python User Install feature (typically triggered by using pip install --user or uv sync --user).
# By default, when you don't use a virtual environment and run a user installation, Python puts packages into a hidden folder in the user's home directory (e.g., ~/.local/).
# Setting PYTHONUSERBASE=/deps overrides that default behavior. It forces Python to treat the /deps folder as its home for user-installed packages instead.
# Why it is used in this Dockerfile
# Using PYTHONUSERBASE=/deps solves three major problems in multi-stage Docker builds when you don't want a virtual environment:
# 1. It groups everything into one predictable folderInstead of packages spreading out across various system folders (like /usr/local/lib/... or /usr/local/bin/...), Python is forced to create a clean, predictable structure inside a single folder:
# Libraries: /deps/lib/python3.14/site-packages/
# Binaries: /deps/bin/

# Copy config files first to leverage docker caching
COPY pyproject.toml uv.lock ./

# Install dependecies without installing the project itself
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project --system


# --- Stage 2: runner stage
FROM python:3.14-alpine3.23 AS runner

WORKDIR /app

# Set Python & uv env variables
ENV PYTHONUSERBASE=/deps \
    PATH="/deps/bin:$PATH" \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1
# Because PYTHONUSERBASE=/deps is set, the Python interpreter automatically looks inside /deps/lib/python3.14/site-packages whenever your code runs an import statement. Adding /deps/bin to the system PATH ensures you can run CLI tools installed by your dependencies (like black, pytest, or gunicorn) directly from the terminal.

# Copy only the dedicated dependency directory
COPY --from=builder /deps /deps

# Copy rest of app code
COPY . .

EXPOSE 8000

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000"]